/// Closed host-internal identifiers whose spellings are fixed at compile time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InternalId {
    OverlayQuery,
    OverlayDecision,
    OverlayDeleteWorkDir,
    OverlaySubmit,
    ProviderRetry,
    ResourceSemanticKey,
    ResourceHeadSha,
    GitHubIssueResource,
    GitHubPullRequestResource,
    RepositoryItem,
    AgentItem,
    SessionItem,
    StatusBucketItem,
    WorkbenchCardItem,
    RepositoryFormName,
    RepositoryFormBaseDir,
    RepositoryFormDefaultProfile,
    RepositoryFormDefaultModel,
    RepositoryFormDefaultYolo,
    RepositoryFormDefaultAgentType,
    RepositoryFormDefaultVersion,
    RepositoryFormDefaultMode,
    RepositoryFormDefaultLlxprtVersion,
    RepositoryFormGithubRepo,
    RepositoryFormIssuePrRepo,
    RepositoryFormRemoteEnabled,
    RepositoryFormLoginUser,
    RepositoryFormHost,
    RepositoryFormSshPort,
    RepositoryFormIdentityFile,
    RepositoryFormSshOptions,
    RepositoryFormRunAsUser,
    RepositoryFormSetupEnvDefault,
    RepositoryFormTransientAgentDir,
    RepositoryFormTransientMaxConcurrent,
    AgentFormShortcut,
    AgentFormName,
    AgentFormDescription,
    AgentFormWorkDir,
    AgentFormProfile,
    AgentFormAgentType,
    AgentFormModel,
    AgentFormVersion,
    AgentFormYolo,
    AgentFormQuickResume,
    AgentFormMode,
    AgentFormLlxprtVersion,
    AgentFormLlxprtDebug,
    AgentFormPassContinue,
    AgentFormSandbox,
    AgentFormSandboxEngine,
    AgentFormSandboxFlags,
}

impl InternalId {
    pub(super) const fn as_str(self) -> &'static str {
        match self {
            Self::OverlayQuery => "query",
            Self::OverlayDecision => "decision",
            Self::OverlayDeleteWorkDir => "delete-work-dir",
            Self::OverlaySubmit => "submit",
            Self::ProviderRetry => "retry",
            Self::ResourceSemanticKey => "semantic-key",
            Self::ResourceHeadSha => "head-sha",
            Self::GitHubIssueResource => "github.issue",
            Self::GitHubPullRequestResource => "github.pull-request",
            Self::RepositoryItem => "host-repository",
            Self::AgentItem => "host-agent",
            Self::SessionItem => "host-session",
            Self::StatusBucketItem => "host-status-bucket",
            Self::WorkbenchCardItem => "host-workbench-card",
            Self::RepositoryFormName => "repository-form-name",
            Self::RepositoryFormBaseDir => "repository-form-base-dir",
            Self::RepositoryFormDefaultProfile => "repository-form-default-profile",
            Self::RepositoryFormDefaultModel => "repository-form-default-model",
            Self::RepositoryFormDefaultYolo => "repository-form-default-yolo",
            Self::RepositoryFormDefaultAgentType => "repository-form-default-agent-type",
            Self::RepositoryFormDefaultVersion => "repository-form-default-version",
            Self::RepositoryFormDefaultMode => "repository-form-default-mode",
            Self::RepositoryFormDefaultLlxprtVersion => "repository-form-default-llxprt-version",
            Self::RepositoryFormGithubRepo => "repository-form-github-repo",
            Self::RepositoryFormIssuePrRepo => "repository-form-issue-pr-repo",
            Self::RepositoryFormRemoteEnabled => "repository-form-remote-enabled",
            Self::RepositoryFormLoginUser => "repository-form-login-user",
            Self::RepositoryFormHost => "repository-form-host",
            Self::RepositoryFormSshPort => "repository-form-ssh-port",
            Self::RepositoryFormIdentityFile => "repository-form-identity-file",
            Self::RepositoryFormSshOptions => "repository-form-ssh-options",
            Self::RepositoryFormRunAsUser => "repository-form-run-as-user",
            Self::RepositoryFormSetupEnvDefault => "repository-form-setup-env-default",
            Self::RepositoryFormTransientAgentDir => "repository-form-transient-agent-dir",
            Self::RepositoryFormTransientMaxConcurrent => {
                "repository-form-transient-max-concurrent"
            }
            Self::AgentFormShortcut => "agent-form-shortcut",
            Self::AgentFormName => "agent-form-name",
            Self::AgentFormDescription => "agent-form-description",
            Self::AgentFormWorkDir => "agent-form-work-dir",
            Self::AgentFormProfile => "agent-form-profile",
            Self::AgentFormAgentType => "agent-form-agent-type",
            Self::AgentFormModel => "agent-form-model",
            Self::AgentFormVersion => "agent-form-version",
            Self::AgentFormYolo => "agent-form-yolo",
            Self::AgentFormQuickResume => "agent-form-quick-resume",
            Self::AgentFormMode => "agent-form-mode",
            Self::AgentFormLlxprtVersion => "agent-form-llxprt-version",
            Self::AgentFormLlxprtDebug => "agent-form-llxprt-debug",
            Self::AgentFormPassContinue => "agent-form-pass-continue",
            Self::AgentFormSandbox => "agent-form-sandbox",
            Self::AgentFormSandboxEngine => "agent-form-sandbox-engine",
            Self::AgentFormSandboxFlags => "agent-form-sandbox-flags",
        }
    }
}

/// The exact closed internal id of a confirmation's decision row.
///
/// The bin crate (mouse routing) needs this without exposing `Id::internal`; it
/// is the only place a raw `"decision"` comparison used to live.
#[must_use]
pub fn overlay_decision_id() -> crate::domain::Id {
    crate::domain::Id::internal(InternalId::OverlayDecision)
}
